[tool.poetry]
name = "pugsql"
version = "0.1.9"
description = "PugSQL is an anti-ORM that facilitates interacting with databases using SQL in files."
authors = ["Dan McKinley <mcfunley@gmail.com>"]
license = "Apache-2.0"
homepage = "https://pugsql.org"
repository = "https://github.com/mcfunley/pugsql"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Topic :: Database :: Front-Ends"
]
readme = "pypi-readme.md"

[tool.poetry.dependencies]
python = ">=3.5"
sqlalchemy = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
pdoc3 = "^0.6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
